const fs=require('fs')
//fs.writeFileSync('sample.txt','sample file created')
//fs.appendFileSync('sample.txt','\nhello svecw ')
//const data=fs.readFileSync('sample.txt','utf-8')
//console.log(data)
//fs.writeFileSync('hello.txt','jhfkwhfmef')
//console.log(data.toString())
//fs.renameSync('sample.txt','example.txt')
//fs.mkdirSync('file')
//fs.rmdirSync('file')
//fs.unlinkSync('example.txt') //delete the hello.txt file
//fs.unlink('async1.txt',()=>{console.log('fjhslf')})
fs.writeFile('Async.txt','this is in async file',()=>{console.log('filecreated')})
fs.writeFile('async1.txt','this is async1',()=>{console.log("async1")})
fs.appendFile("async1.txt","Async",()=>{console.log('jdkjdl')})
const readval=fs.readFile("Async.txt",()=>{console.log('read')})
console.log(readval)